name: ecommerce_hoang
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.12
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  flutter_screenutil: ^5.3.1
  fluttertoast: ^8.0.9
  dots_indicator: ^2.1.0
  carousel_slider: ^4.0.0


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true